# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0057_auto_20170725_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherinfo',
            old_name='dateTime',
            new_name='date',
        ),
    ]
